### ISSUE TITLE
License needed in osr project

### ISSUE THREAD

**Issue by robekeane** [opensource-rainforest/osr#1]
There's no license listed in this repo, we shoud add one. @genedna How about [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by genedna** [comment]
@robekeane,

Thanks for the reminder, and please contribute a PR about the license to help us.
Let's discuss it with other members in the PR thread.

The project and repository are for the Chinese users, maybe use Chinese for the furture.

**Comment by robekeane** [comment]
Cool, 

> @robekeane,
> 
> Thanks for the reminder, and please contribute a PR about the license to help us. Let's discuss it with other members in the PR thread.
> 
> The project and repository are for Chinese users, maybe use Chinese in the future.

@genedna Cool, I'm looking forward to others' review. Thanks for your advice.

**Comment by king-gao** [comment]
> 

/LGTM
