### ISSUE TITLE
是否增加 CC 4.0 中文版本 License 

### ISSUE THREAD

**Issue by genedna** [opensource-rainforest/osr#14]
**CC 4.0** 有官方的中文版本 [License](https://creativecommons.org/licenses/by-sa/4.0/legalcode.zh-Hans) ，是否要做本代码仓库中增加。

**Comment by king-gao** [comment]
@genedna 我的意见：不建议增加，因为中文的翻译可能会产生歧义。建议还是保留英文的原汁原味的好一点，我的意见。

**Comment by genedna** [comment]
> @genedna 我的意见：不建议增加，因为中文的翻译可能会产生歧义。建议还是保留英文的原汁原味的好一点，我的意见。

好的，那还是用英文的版本作为主 License
