### ISSUE TITLE
开源雨林这类文档类的开源项目 GFDL、CC BY SA 孰更适合？

### ISSUE THREAD

**Issue by Ameliawangyumao** [opensource-rainforest/osr#17]

**Comment by robekeane** [comment]
建议使用CC BY-SA 4.0 License，
理由：
1、必须署名、再分发须以相同license发布、可商用，CC BY-SA 4.0 License可满足这些需求，且只需要附带链接，比GFDL全文引用更方便。
2、CC BY-SA 4.0 License应用场景广且判例丰富，GFDL未见有司法判例公开。
3、虽然都有ShareAlike条款，但CC BY-SA 4.0 License可以与GPL单向兼容（CC与GNU官方合作后CC声明），但GFDL与GPL因为ShareAlike条款的兼容性问题未有任何官方说法，因此从法律层面来说GFDL与GPL仍无法兼容。
详细解读可以参考：https://docs.google.com/presentation/d/1UVsAT5P7d5FDMg7It7qyVQZCKFbNNeNV/edit?usp=sharing&ouid=103987571222707969054&rtpof=true&sd=true

**Comment by genedna** [comment]
同意 @robekeane 的建议，继续沿用当前版本 License
