### ISSUE TITLE
we can discuss the framework and content of the training project.

### ISSUE THREAD

**Issue by king-gao** [opensource-rainforest/osr#3]
we have plan 7 classes now. Including the following content:
- 《Open Source Culture and Awareness》
- 《Open Source Use and Best Practise》
- 《Open Source Ecosystem Build and Best Practise》
- 《Open Source Compliance and Risk Managment》
- 《Open Soure Security and Risk Managment》
- 《Open Surce Lifecycle Managment》
- 《Enterprise Strategy and Bussiness Modle》

IF you have any suggestion, you can comment follow.

**Comment by genedna** [comment]
LGTM and I initialled scratch of the book with #4.
