### ISSUE TITLE
关于 README 中对开源雨林有 xxx 等组织发起的疑问

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-rainforest/osr#45]
如题，是由更多的组织发起吗？如果是的话，有地方能看到完整名单吗？按理说，发起单位或组织是固定的，不会随着时间推移而改变的。那既然是固定的，就应该由完整的名单，加上“等等“这样的表述，会很难理解到底是谁们发起的。

![image](https://user-images.githubusercontent.com/1450685/234834429-998f1dfd-5bb1-402d-8f7f-d8633168f61f.png)

**Comment by HackYardo** [comment]
As far as I know, "等" can be used for "煞尾" as well, check it out.

**Comment by LinuxSuRen** [comment]
> As far as I know, "等" can be used for "煞尾" as well, check it out.

As you mentioned. There will be a number following it in this case. Such as: `有 A、B、C 等 4 个选项`.

**Comment by LinuxSuRen** [comment]
Forget about this.
